# Generated by Django 5.0.3 on 2024-04-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='portfolio',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='state',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
