# Generated by Django 5.0.3 on 2024-04-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0004_alter_trail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='weather',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
