# Generated by Django 5.0.3 on 2024-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0009_alter_trail_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
