# Generated by Django 5.0.3 on 2024-04-26 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0011_managerassessmentrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trail_app.state')),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='managerassessmentrecord',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail_app.user'),
        ),
    ]
