# Generated by Django 5.0.3 on 2024-04-26 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0012_user_alter_managerassessmentrecord_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='belong_state',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trail_app.trail')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='trailFolder',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='trail_app.trailfolder'),
            preserve_default=False,
        ),
    ]
