# Generated by Django 5.0.3 on 2024-04-26 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0013_remove_user_belong_state_user_name_trailfolder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailfolder',
            name='trail',
        ),
        migrations.AddField(
            model_name='trail',
            name='trailFolder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trail_app.trailfolder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailfolder',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
