# Generated by Django 5.0.3 on 2024-04-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trail_app', '0015_trailfolders_alter_trail_trailfolder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='trailFolder',
        ),
    ]
